### ISSUE TITLE
Corrupted sprites on Virtua Fighter Animation / Mini

### ISSUE THREAD

**Issue by john-reno** [PocketSprite/8bkc-gamegear#1]
Reproducible if you select "large" mode on the character select screen. Large sprites appear jumbled and glitchy - works fine in other Game Gear emulators. Image attached, let me know if I can provide any more information! 
![vf-glitch](https://user-images.githubusercontent.com/30169674/41828580-659efa98-7879-11e8-84f6-64b9789dc069.jpg)

**Comment by Spritetm** [comment]
Should be fixed in #c8021bd3a9abd50b9e3

**Comment by john-reno** [comment]
Works perfectly!
